service: serverless-appsync-backend

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-2

plugins:
  - serverless-appsync-plugin

custom:
  appSync:
    name: youtubeAppSyncAPI
    authenticationType: AMAZON_COGNITO_USER_POOLS
    additionalAuthenticationProviders:
      - authenticationType: AWS_IAM
    userPoolConfig:
      awsRegion: us-east-2
      defaultAction: ALLOW
      userPoolId: !Ref cognitoUserPool
    mappingTemplatesLocation: mapping-templates
    mappingTemplates:
      - dataSource: booksTable
        type: Query
        field: getBookById
      - dataSource: booksTable
        type: Mutation
        field: createBook
    dataSources:
      - type: AMAZON_DYNAMODB
        name: booksTable
        config:
          tableName: !Ref booksTable

resources:
 Resources:
  ${file(resources.yml)}